{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    release: {{ .Values.prometheus.releaseLabel }}
spec:
  selector:
    matchLabels:
      app: {{ include "python-app.name" . }}
  endpoints:
    - port: metrics
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
{{- end }}
